### ISSUE TITLE
min_clock conky - Cannot change text color on lua

### ISSUE THREAD

**Issue by tcom01** [easysid/conky_configs#1]
On this section of the lua:

```
    -- color settings. {color, alpha}
    background_color = {0xFFFFFF, 0.0}, -- bgcolor id draw_background is true.
    fill_color   = {0xb5145c, 1},       -- fill color for minutes ring
    border_color = {0xFFFF00, 1},       -- border color
    text_color   = {0xFF0000, 1},       -- color of numbers
    -- font settings
```

I tried a variety of colors on the "text_color" entry, but no matter what I use, the font/text remains white. As you can see above, I tried red [FF0000], but no change. The other two, fill_color and border_color work fine. I would like to be able to change the font/text color of this conky.

**Comment by easysid** [comment]
Hi,
Thanks for noticing this. It was an error on my part. The "text_color" was never passed to the out() function to set the color. 667c4437 fixes it.

Note that "text_color" will now control the colors of all the texts - hours, day, and minutes. If you wish to have the option for different colors, drop me a mail. :)

Thanks.

**Comment by tcom01** [comment]
Outstanding! Thanks for the quick fix.
