### ISSUE TITLE
hi conky

### ISSUE THREAD

**Issue by tjw0lf** [easysid/conky_configs#3]
How do you get the Click-Clock to work nothing in text

**Comment by easysid** [comment]
Yes, the text portion is left blank in the conkyrc, all the stuff is generated in the lua script.

Are you getting any errors?

**Comment by tjw0lf** [comment]
Thank you very much for getting back to me. Awesome work on conky I know its been long time since this was made probably. 

OK i thought it needed text. Then for some reason its not showing at all. I'm running Conky manager 2.4 and make a folder and the .conkyrc file and then add the lua and change the location to mine in .conky folder. But nothing shows up.

I will try again. But can you check for me to see if this still works with conky manager 2.4.

I can also put whatever command you want me to put in terminal to find out the problem for you. Running it under Ubuntu based 14.04 Linux lite

**Comment by tjw0lf** [comment]
Ok disregard these messeges its working fine. Seems i didn't need to change anything work flawlessly in conky manager 2.4

**Comment by easysid** [comment]
Glad it worked out for you. Did you find out what was causing the problem?

**Comment by tjw0lf** [comment]
ya it was my mistake. I had put the file location name in the conkyrc as /.conky/click_clock I think for the lua to be found. But i did not need to change anything so this time i did not and all works fine. Its one of the creative conkys i have seen awesome

**Comment by easysid** [comment]
Thanks. Closing...
